### ISSUE TITLE
Can't include other components

### ISSUE THREAD

**Issue by chrisjaure** [thetalecrafter/hexo-renderer-react#1]
I'm trying to import components defined in the theme to use in a page, but it seems that is not intended to work since the dependencies don't get run through babel so the compiler is choking on the non-transpiled es6 syntax. Is that correct? What is the appropriate way to include theme components in a page?

**Comment by vanwagonet** [comment]
Maybe this should use babel/register. I'd love it if you submitted your solution in a pull request.
